spring.application.name=ecosistema
spring.datasource.url=jdbc:mariadb://localhost:3306/Ecos
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=681539980222-aq9872eh504e97tntnp6u6hdqvkhhoko.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile, email

cloudinary.cloud_name=dyb7cwvgz
cloudinary.api_key=599862417877693
cloudinary.api_secret=aCT0x1D4mJVmteBomxwATcixv9k

SECRET_KEY=fsdfs46151@fde
API_KEY=04a3964a4b7d41a68aeb99ab2ea205a5


email.username:matiasllanos1998@gmail.com
email.password:aoip fnnc xmji zupo

