spring.application.name=ecosistema
spring.datasource.url=jdbc:mariadb://localhost:3306/Ecos
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=${SPRING_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email

cloudinary.cloud_name=dyb7cwvgz
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}

SECRET_KEY=${SECRET_KEY}
API_KEY=${API_KEY}


email.username:${EMAIL}
email.password:${EMAIL_PASSWORD}

